name: chuck_norris_tinder
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ^2.17.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  json_annotation: 4.5.0
  dio: 4.0.6
  auto_size_text: ^3.0.0
  url_launcher: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.1.7
  json_serializable: ^6.2.0

flutter_icons:
  image_path: assets/logo/logo.png
  android: true

flutter:
  uses-material-design: true
